### ISSUE TITLE
[Bug]: Config File Mishap?

### ISSUE THREAD

**Issue by P4YN-Ki** [Fuzss/magnumtorch#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.2

### Notes (Required)

This isn't a bug that effects gameplay, just one that affects OCD. In the Config file magnumtorch-server.toml each torch has it's setting explained twice.... per torch. If you're using Notepad++ It looks like this.

Line 16: #Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). Etc etc
Go down a few lines and it's there again
Line26: #Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). Etc Etc
This is still the settings for [diamond_torch]. It does it again for,
[emerald_torch] at Line: 64 & Line: 74
[amethyst_torch] at Line: 112 & Line: 122

Again this doesn't really affect anything but my OCD and it really threw me off when I was first setting up the mod (which I love btw). So yeah, maybe we can fix this? please?

**Comment by Fuzss** [comment]
Please share your config file.

**Comment by P4YN-Ki** [comment]
So I can't drag and drop the file type here because _github_ doesn't support .toml files apparently. So, I'll copy & paste the contents here as well as upload a copy of it to my mega account. Mega Link: https://mega.nz/file/gQwBRC5Z#DDZ579cQSmdDpR58jZHz3TtJSx_xdrYF7qpm4aWmw1w

I've marked the areas as **_Bold & Italics_** so they are easier to spot. I'll also note, that I've removed the excess text from the config file and as as soon as I launch my game, they revert to having the duplicated text

[magnumtorch-server.toml]

[diamond_torch]
	#Mobs that should still be allowed to spawn despite being included in "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_whitelist = []
	#Mobs that should not be allowed to spawn despite being absent from "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_blacklist = []
	#Type of shape used for calculating area in which spawns are prevented.
	#This basically let's you choose between taxi cab or euclidean metrics.
	#Allowed Values: ELLIPSOID, CYLINDER, CUBOID
	shape_type = "CUBOID"
	#Range for preventing mob spawns on y-dimension.
	#Range: > 0
	vertical_range = 64
	_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids._
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers
	**_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids.
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers_**
	#Allowed Values: NATURAL, SPAWNER, STRUCTURE, MOB_SUMMONED, JOCKEY, EVENT, REINFORCEMENT, PATROL, TRIGGERED
	blocked_spawn_types = ["NATURAL", "EVENT", "JOCKEY", "REINFORCEMENT", "TRIGGERED", "STRUCTURE"]
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT
	mob_category = ["MONSTER"]
	#Range for preventing mob spawns on x-z-plane.
	#Range: > 0
	horizontal_range = 128

[emerald_torch]
	#Mobs that should still be allowed to spawn despite being included in "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_whitelist = []
	#Mobs that should not be allowed to spawn despite being absent from "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_blacklist = []
	#Type of shape used for calculating area in which spawns are prevented.
	#This basically let's you choose between taxi cab or euclidean metrics.
	#Allowed Values: ELLIPSOID, CYLINDER, CUBOID
	shape_type = "CUBOID"
	#Range for preventing mob spawns on y-dimension.
	#Range: > 0
	vertical_range = 64
	_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids._
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers
	**_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids.
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers_**
	#Allowed Values: NATURAL, SPAWNER, STRUCTURE, MOB_SUMMONED, JOCKEY, EVENT, REINFORCEMENT, PATROL, TRIGGERED
	blocked_spawn_types = ["PATROL", "EVENT"]
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT
	mob_category = ["CREATURE"]
	#Range for preventing mob spawns on x-z-plane.
	#Range: > 0
	horizontal_range = 128

[amethyst_torch]
	#Mobs that should still be allowed to spawn despite being included in "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_whitelist = []
	#Mobs that should not be allowed to spawn despite being absent from "mob_category".
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_blacklist = []
	#Type of shape used for calculating area in which spawns are prevented.
	#This basically let's you choose between taxi cab or euclidean metrics.
	#Allowed Values: ELLIPSOID, CYLINDER, CUBOID
	shape_type = "CUBOID"
	#Range for preventing mob spawns on y-dimension.
	#Range: > 0
	vertical_range = 32
	_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids._
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers
	**_#Types of mob spawns to block (provided by vanilla, some seem a little arbitrary). By default this is configured to only affect natural spawns occurring without player interaction and to not disrupt any game events such as raids.
	#NATURAL: monsters spawned during night time, cats in villages, phantoms in the sky
	#SPAWNER: all kinds of mobs summoned by monster spawners
	#STRUCTURE: zombified piglin from nether portals
	#MOB_SUMMONED: iron golems from villagers
	#JOCKEY: mobs spawned as a rider for another mob
	#EVENT: mobs spawned by game events, mainly zombie sieges, raids, wandering trader visits
	#REINFORCEMENT: zombie reinforcements spawned when a zombie is hurt
	#PATROL: pillager patrols
	#TRIGGERED: skeleton horse traps and warden from sculk shriekers_**
	#Allowed Values: NATURAL, SPAWNER, STRUCTURE, MOB_SUMMONED, JOCKEY, EVENT, REINFORCEMENT, PATROL, TRIGGERED
	blocked_spawn_types = ["NATURAL"]
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Mobs of this category are prevented from spawning through natural means (e.g. mob spawners and breeding will still work).
	#For refining affected mobs use blacklist and whitelist options.
	#If you only want to prevent a few mob types from spawning that do not fit any category leave this list empty and include them in the blacklist option.
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT
	mob_category = ["AMBIENT", "AXOLOTLS", "WATER_AMBIENT", "WATER_CREATURE", "UNDERGROUND_WATER_CREATURE"]
	#Range for preventing mob spawns on x-z-plane.
	#Range: > 0
	horizontal_range = 64


I hope this helps. Like I said, it doesn't have any negative effect as far as I can tell. It just simply triggers my OCD.

EDIT: Added Bold & Italics to duplicated text.

**Comment by Fuzss** [comment]
So I don't really have much control over this, it just looks like a mishap with your file, deleting it should be good enough for letting a proper one generate.
In the end this comes down to an issue with the config system which is managed by Forge not me.
