### ISSUE TITLE
[Question]: Recipe output preview is a knowledge book

### ISSUE THREAD

**Issue by WnndGws** [Fuzss/magnumtorch#13]
### Suggestion (Required)

I hope this is a fine place to ask, since I love all your mods

The recipe output for all the custom recipes is a knowledge book, but I see on the screenshots on Modrinth that it previews the torch ([example](https://wsrv.nl/?url=https%3A%2F%2Fmedia.forgecdn.net%2Fattachments%2F440%2F545%2F2022-03-13_10.png&n=-1))

It is the same for all recipes, and other than that, they work perfectly! I'm just wondering if I missed something.

TIA!

**Comment by WnndGws** [comment]
False Report! Sorry! Love your work

**Comment by Fuzss** [comment]
Thank you!
