### ISSUE TITLE
[Bug]: Chicken Spawninng

### ISSUE THREAD

**Issue by DarthDuroq** [Fuzss/magnumtorch#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Current Behavior: 
1. Place diamond magnum torch.
2. Spawning of disappearing chickens on non-grass blocks.

Expected Behavior:
No spawning of mobs, especially chickens, on non-grass blocks within area covered by torch.

Suspected Cause:
Suspect zombie chicken riders attempt to spawn, zombie portion is likely blocked by torch but passive animal (chicken) is allowed to continue spawning. This would match up with their tendency to despawn and their lack of egg-laying capacity, pointing to them being the jockey-type chickens.

**Comment by Fuzss** [comment]
For now you can manually add chickens to the diamond torch in the config. Additionally make sure `JOCKEY` is included in the blocked types. This will not interfere with normal chickens as they don't spawn on the spawning cycle (technically they do, but there is usually more than 10 animals in a world so the animal spawning cycle almost never runs).

**Comment by DarthDuroq** [comment]
I wanted to both confirm that JOCKEY was a blocked type in the config and update you on an interesting part of this bug. If the jockey-type chickens are present on closing the world, when the world is reopened not only are the chickens still present but their baby zombie riders reappear as well. Also, unfortunately adding chickens to the config would interfere with my use case because its a sky-block-style map and I actually rely on the animal spawning cycle.

**Comment by Fuzss** [comment]
Fixed in 1.20.1+, no config changes required.
