### ISSUE TITLE
[Crash]: Crashing when added to the ATM9 modpack

### ISSUE THREAD

**Issue by TeKett** [Fuzss/magnumtorch#18]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

During startup loading of mods

### Crash Report (Required)

https://gist.github.com/TeKett/9f9e2a0ab92d7ec304607b9d495b4843

**Comment by Fuzss** [comment]
Looks like a nochatreports issue to me.

**Comment by Fuzss** [comment]
Closing this, as the report has no trace of Magnum Torch being involved in any way.
