### ISSUE TITLE
[Trivial]: Curseforge description technically wrong

### ISSUE THREAD

**Issue by kyragit** [Fuzss/magnumtorch#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

N/A

### Mod Version (Required)

N/A

### Notes (Required)

The mod description says that passive mobs only spawn during world generation and breeding, which is [not true](https://technical-minecraft.fandom.com/wiki/Passive_mob_farming). Not exactly a huge deal, but there you go.

**Comment by Fuzss** [comment]
Thanks, I'll be redoing the pages anyways.
