### ISSUE TITLE
[Crash]: crash

### ISSUE THREAD

**Issue by Rogenar** [Fuzss/magnumtorch#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

v5.0.0

### Notes (Required)

the game crashed before it even started
[latest.log](https://github.com/Fuzss/magnumtorch/files/11083639/latest.log)

### Crash Report (Required)

[latest.log](https://github.com/Fuzss/magnumtorch/files/11083639/latest.log)

**Comment by Fuzss** [comment]
Thanks, fixed in v5.0.1.

**Comment by Rogenar** [comment]
can i ask you for some help?

**Comment by Fuzss** [comment]
https://lunapixel.studio/discord

**Comment by Rogenar** [comment]
It wasn't very important. I'm just having a conflict in a common item description by 2 different mods. Can I fix this with another mod or do you know a 1.19.3 fabric mod that can solve it?

**Comment by Fuzss** [comment]
I have no clue, but ask on the discord and explain what specifically you want to do. There are more people there that can help you.
